owner: FxllenCode # GitHub username
repo: StatusPlus # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
assignees: # Users to assign downtime issues (optional)
  - FxllenCode
status-website: # Status website (optional)

  baseUrl: /StatusPlus
  name: Status+ # Status website title

  # why dude