owner: Status-Plus # GitHub username
repo: StatusPlus # GitHub repository name
sites: # List of endpoints to track
  - name: Roblox Site
    url: https://www.roblox.com
    maxResponseTime: 1000

  - name: Roblox Devforum
    url: https://devforum.roblox.com
    maxResponseTime: 1000

  - name: Roblox Devhub
    url: https://developer.roblox.com
    maxResponseTime: 1000

  - name: Avatar API Endpoint
    url: https://avatar.roblox.com/v1/avatar-rules
    method: GET
    maxResponseTime: 1000

  - name: Badges API Endpoint
    url: https://badges.roblox.com/v1/badges/2124548403
    method: GET
    maxResponseTime: 1000

  - name: Roblox's CDN API Endpoint
    url: http://cdnproviders.roblox.com/
    method: GET
    maxResponseTime: 1000   

  - name: Catalog API Endpoint
    url: https://catalog.roblox.com/v1/bundles/details?bundleIds=192
    method: GET
    maxResponseTime: 1000

  - name: Datastore API Endpoint
    url: https://gamepersistence.roblox.com/
    method: GET
    maxResponseTime: 1000

  - name: Develop API Endpoint
    url: https://develop.roblox.com/v1/toolbox/items?category=Hat&keyword=Hat
    method: GET
    maxResponseTime: 1000

  - name: Friends API Endpoint
    url: https://friends.roblox.com/v1/metadata
    method: GET
    maxResponseTime: 1000

  - name: Game Join API Endpoint
    url: http://gamejoin.roblox.com/
    method: GET
    maxResponseTime: 1000    

  - name: Groups API Endpoint
    url: https://groups.roblox.com/v1/groups/configuration/metadata
    method: GET
    maxResponseTime: 1000

  - name: Inventory API Endpoint
    url: https://inventory.roblox.com/v1/users/82738847/assets/collectibles?limit=10&sortOrder=Asc
    method: GET
    maxResponseTime: 1000

  - name: Text Filter API Endpoint
    url: http://textfilter.roblox.com/
    method: GET
    maxResponseTime: 1000

  - name: Thumbnails API Endpoint
    url: https://thumbnails.roblox.com/v1/assets?assetIds=82738847&format=Png&isCircular=false&size=30x30
    method: GET
    maxResponseTime: 1000

# ????

# e

assignees: # Users to assign downtime issues (optional)
  - FxllenCode
status-website: # Status website (optional)
  baseUrl: /StatusPlus
  logoUrl: https://raw.githubusercontent.com/Status-Plus/StatusPlus/master/Standalone/SVG/Full.svg
  name: Status +
  publish: true
  hideNavTitle: true
  scripts:
      - src: https://www.googletagmanager.com/gtag/js?id=G-97T3SSH4DV
        async: true
  js: "window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-97T3SSH4DV');"
  navbar:
      - title: Status
        href: /StatusPlus
      - title: GitHub
        href: https://github.com/FxllenCode/StatusPlus
  introTitle: "**Status + is a free, automated alternative to Roblox's Status Site."
  introMessage: This uses real-time information from roblox's API endpoints to determine if there is any slowness/outages. This can detect outages faster than Roblox's status site as this is automated. It can also be used inside Roblox games. This part of Status + is called DowntimeService.

  faviconSvg: https://raw.githubusercontent.com/Status-Plus/StatusPlus/master/Standalone/SVG/PlusLogo.svg
  favicon: https://raw.githubusercontent.com/Status-Plus/StatusPlus/master/Standalone/PNG/Icon%20Only/PlusLogo-192h.png

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "*/5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  footer: Made with ❤️ by [Status +](https://github.com/Status-Plus/StatusPlus), 🔌 by [Upptime.](https://github.com/upptime/upptime)
  